version: '3.3'
services:

  backend:
    container_name: backend
    build:
      context: ../src
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:8000"
    env_file:
      - ./.env

  external_api:
    container_name: external_api
    build:
      dockerfile: Dockerfile
      context: ../src_ext
    ports:
      - "8000:8000"
    env_file:
      - ./.ext_env

  redis_ext:
    container_name: redis_ext
    image: redis:6.2-alpine

  celery_worker_ext:
    container_name: celery_worker_ext
    build:
      context: ../src_ext
    command: celery -A tasks.tasks:celery worker --loglevel=INFO
    env_file:
      - ./.ext_env
    depends_on:
      - external_api
      - redis_ext

  flower_ext:
    container_name: flower_ext
    build:
      context: ../src_ext
    command: celery -A tasks.tasks:celery flower --port=5555
    ports:
      - "5555:5555"
    env_file:
      - ./.ext_env
    depends_on:
      - external_api
      - redis_ext
      - celery_worker_ext
